events { worker_connections 1024; }

http {
  upstream storefront {
    server storefront:3000;
  }

  upstream admin {
    server admin:3001;
  }

  upstream api {
    server api:4000;
  }

  server {
    listen 80;

    # API Routing
    location /api/ {
      proxy_pass http://api;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Uploads Static Assets
    location /uploads/ {
      proxy_pass http://api;
      proxy_set_header Host $host;
    }

    # Admin Portal Routing
    location /admin {
      proxy_pass http://admin;
      proxy_set_header Host $host;
    }

    # Storefront Default
    location / {
      proxy_pass http://storefront;
      proxy_set_header Host $host;
    }
  }
}
